/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_H_
# define SHADER_H_
# define VAR_COLOR "M"
# define VAR_IRESOLUTION "v"

const char *shader_frag =
 "#version 450\n"
 "uniform vec2 v;"
 "vec2 d=(gl_FragCoord.xy.xy/v*2-1)*vec2(1,v.y/v.x);"
 "out vec3 M;"
 "float l=.001;"
 "vec3 m=vec3(0.,0.,-6.),f=normalize(vec3(d,1)),r=m,i[3],s[3];\n"
 "#define B vec3(-.015)\n"
 "#define R vec3(.4,.0,.0)\n"
 "#define G vec3(.03)\n"
 "float n(vec2 v)"
 "{"
   "return v=fract(v*vec2(233.34,851.74)),v+=dot(v,v+23.45),fract(v.x*v.y);"
 "}"
 "vec3 n(vec3 d,vec3 v)"
 "{"
   "float f=cos(v.x),r=sin(v.x);"
   "mat3 M=mat3(vec3(1,0,0),vec3(0,f,-r),vec3(0,r,f));"
   "f=cos(v.y);"
   "r=sin(v.y);"
   "M*=mat3(vec3(f,0,r),vec3(0,1,0),vec3(-r,0,f));"
   "f=cos(v.z);"
   "r=sin(v.z);"
   "M*=mat3(vec3(f,-r,0),vec3(r,f,0),vec3(0,0,1));"
   "return M*d;"
 "}struct MA{float d;vec3 col;bool hit;};"
 "float t(vec2 v)"
 "{"
   "return dot(v,v);"
 "}"
 "MA n(vec3 v,float f,float d,float r,float M,vec3 m)"
 "{"
   "vec2 s=vec2(length(v.xz),v.y),i=vec2(r,f),x=vec2(r-d,2.*f),y=vec2(s.x-min(s.x,s.y<0.?d:r),abs(s.y)-f),n=s-i+x*clamp(dot(i-s,x)/t(x),0.,1.);"
   "float l=n.x<0.&&y.y<0.?-1.:1.,a=l*sqrt(min(t(y),t(n)))-M;"
   "return MA(a,m,false);"
 "}"
 "MA n(vec3 v,vec3 d,float M,vec3 f)"
 "{"
   "vec3 r=abs(v)-d;"
   "float m=length(max(r,0.))+min(max(r.x,max(r.y,r.z)),0.)-M;"
   "return MA(m,f,false);"
 "}"
 "MA t(vec3 v,vec3 f,float d,vec3 r)"
 "{"
   "float M=dot(v,f)+d;"
   "return MA(M,r,false);"
 "}"
 "MA t(MA v,MA r)"
 "{"
   "return v.d<r.d?v:r;"
 "}"
 "MA e(MA v,MA r)"
 "{"
   "return v.d>r.d?v:r;"
 "}"
 "float e(float v,float f,float r)"
 "{"
   "float M=max(r-abs(v-f),0.);"
   "return min(v,f)-M*M*.25/r;"
 "}"
 "MA e(vec3 v)"
 "{"
   "v=n(n(v,vec3(-.7,0.,-.04)),vec3(0,1.1,0));"
   "v.y-=1.05;"
   "v.x+=.5;"
   "MA f=t(v+vec3(0,1.25,0),vec3(0,1,0),1.,G),r=n(v+vec3(0,.1,0),1.,.15,.25,0,R),M=n(v+vec3(0,.6,0),.05,.3,.3,.05,B),s=n(v+vec3(0,1.,0),.3,.6,.6,.05,B),d=n(v+vec3(0,1.4,0),vec3(.9,.15,.9),.1,B),i=n(v+vec3(1.75,1.34,.75),.05,.55,.45,.02,R);"
   "i.d-=.0005;"
   "MA m=n(v+vec3(1.75,1.34,-.75),.05,.55,.45,.02,R);"
   "i.d-=.0005;"
   "MA x=n(v+vec3(1.75,1.27,.75),.05,.4,.4,.015,R),y=n(v+vec3(1.75,1.27,-.75),.05,.4,.4,.015,R),z=n(v+vec3(.5,1.85,0),vec3(1.55,0.,1.05),.45,B),l=n(v+vec3(10,sin(v.x*1.8)*.1+2.05,sin(sin(v.x*.7))+.75),vec3(8,0,0),.1,B),a=n(v+vec3(0.,-1.,0.),vec3(0),.5,R);"
   "vec3 c=mod(v,.0001)-5e-05;"
   "MA h=n(c,vec3(0.),n(v.xz)*.002,B);"
   "f.d=mix(f.d,h.d,.05);"
   "v=n(n(v,vec3(-.5,0,0)),vec3(0,1.5,0));"
   "MA o=MA(0.,B,true);"
   "o.d=e(s.d,d.d,.15);"
   "o.d=e(o.d,M.d,.05);"
   "a=t(a,r);"
   "a=t(a,z);"
   "a.d=mix(a.d,h.d,.3);"
   "a=t(a,o);"
   "a=t(a,i);"
   "a=t(a,m);"
   "a=t(a,x);"
   "a=t(a,y);"
   "a=t(a,f);"
   "a=t(a,l);"
   "return a;"
 "}"
 "MA n(vec3 v,vec3 d,float f)"
 "{"
   "MA M;"
   "while(distance(v,r)<f&&!M.hit)"
     "r+=M.d*d,M=e(r),M.hit=M.d<l;"
   "return M;"
 "}"
 "vec3 x(vec3 v)"
 "{"
   "mat3 M=mat3(v,v,v)-mat3(.005);"
   "return normalize(e(v).d-vec3(e(M[0]).d,e(M[1]).d,e(M[2]).d));"
 "}"
 "float e(in vec3 v,in vec3 d,float M,float r,float f)"
 "{"
   "float a=1.,i=1e+20;"
   "for(float x=M;x<r;)"
     "{"
       "float m=e(v+d*x).d;"
       "if(m<.001)"
         "return 0.;"
       "float y=m*m/(2.*i),s=sqrt(m*m-y*y);"
       "a=min(a,f*s/max(0.,x-y));"
       "i=m;"
       "x+=m;"
     "}"
   "return a;"
 "}"
 "vec3 e(vec3 v,vec3 r,vec3 d,float M)"
 "{"
   "vec3 a;"
   "float m[4],x[4];"
   "for(int l=0;l<3;l++)"
     "{"
       "m[l]=max(0.,dot(reflect(i[l],r),f));"
       "x[l]=pow(m[l],64);"
       "float y=e(v,i[l],.1,20.,25);"
       "a+=(m[l]*M*.333+x[l]*M*3)*s[l]*y;"
     "}"
   "return d+a;"
 "}"
 "void main()"
 "{"
   "i[0]=normalize(vec3(0,10,-2.));"
   "i[1]=normalize(vec3(-50,20.,-50.));"
   "i[2]=normalize(vec3(-50,60.,-7.));"
   "vec2 v=vec2(.5,.7);"
   "s[0]=v.xxy*2;"
   "s[1]=v.xyx;"
   "s[2]=v.yxx*.75;"
   "MA a=n(m,f,20);"
   "vec3 d=x(r);"
   "if(a.hit)"
     "{"
       "M=a.col;"
       "M=e(r,d,a.col,.1);"
       "if(a.col==B)"
         "{"
           "r-=f*.01;"
           "f=normalize(reflect(f,d));"
           "a=n(r,f,2.5);"
           "if(a.hit)"
             "M=mix(M,e(r,x(r),a.col,.1),.1);"
         "}"
     "}"
   "M*=1.-distance(m,r)*.05;"
   "M=pow(M,vec3(.4545));"
 "}";

#endif // SHADER_H_
