/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_H_
# define SHADER_H_
# define VAR_RUNTIME "v"

const char *shader_frag =
 "uniform float v[3];"
 "float m=v[0],f=v[2]/v[1];"
 "float x(vec3 v,vec3 x,float y)"
 "{"
   "vec3 m=abs(v)-x;"
   "return length(max(m,0.))+min(max(m.x,max(m.y,m.z)),0.)-y;"
 "}"
 "mat2 x(float v)"
 "{"
   "return mat2(cos(v),sin(v),-sin(v),cos(v));"
 "}"
 "float x(vec3 v,float y)"
 "{"
   "return length(v)-y;"
 "}"
 "float n(vec3 v,vec2 y)"
 "{"
   "vec2 m=vec2(length(v.xz)-y.x,v.y);"
   "return length(m)-y.y;"
 "}"
 "float n(vec3 v,float m,float y,float x)"
 "{"
   "vec2 f=vec2(length(v.xz)-2.*m+y,abs(v.y)-x);"
   "return min(max(f.x,f.y),0.)+length(max(f,0.))-y;"
 "}"
 "float h(vec3 v,float y)"
 "{"
   "v=abs(v);"
   "float m=v.x+v.y+v.z-y;"
   "vec3 f;"
   "if(3.*v.x<m)"
     "f=v.xyz;"
   "else"
     " if(3.*v.y<m)"
       "f=v.yzx;"
     "else"
       " if(3.*v.z<m)"
         "f=v.zxy;"
       "else"
         " return m*.57735;"
   "float x=clamp(.5*(f.z-f.y+y),0.,y);"
   "return length(vec3(f.x,f.y-y+x,f.z-x));"
 "}"
 "float h(vec3 v)"
 "{"
   "v=mod(v,8)-4.;"
   "float f=n(v,vec2(2.,.4)),s=x(v,vec3(1.),.05),a=x(v,2.),y=n(v,1.,.5,.01),c=h(v,2.);"
   "return mix(y,c,sin(m*.5)*.5+.5);"
 "}"
 "vec3 n(vec3 v)"
 "{"
   "vec2 m=vec2(.005,0);"
   "return normalize(vec3(h(v+m.xyy)-h(v-m.xyy),h(v+m.yxy)-h(v-m.yxy),h(v+m.yyx)-h(v-m.yyx)));"
 "}"
 "void main()"
 "{"
   "vec2 m=(gl_FragCoord.xy/vec2(v[1],v[2])-.5)/vec2(f,1);"
   "vec3 x=vec3(0.,0.,-3.),y=x,c=normalize(vec3(m,1.));"
   "float l=0.;"
   "vec3 r;"
   "for(float i=0;i<300.;i++)"
     "{"
       "float a=h(y);"
       "if(a<.01)"
         "{"
           "l=y/.1;"
           "vec3 s=n(y),z=vec3(.5,.8,.2);"
           "float e=dot(s,normalize(z))*.5+.5;"
           "vec3 t=reflect(normalize(z),s);"
           "float o=pow(max(dot(c,t),0),32);"
           "r+=mix(vec3(0.,0.,0.),vec3(1.,0.,0.),e*.5);"
           "r+=mix(r,vec3(.75),o);"
           "break;"
         "}"
       "y+=a*c;"
     "}"
   "float z=length(x-y);"
   "r*=mix(r,vec3(1.,1.,1.),1-exp(-.1*z*z));"
   "gl_FragColor=vec4(r,1);"
 "}";

#endif // SHADER_H_
