/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_H_
# define SHADER_H_
# define VAR_COLOR "m"
# define VAR_IRESOLUTION "v"

const char *shader_frag =
 "#version 460\n"
 "uniform vec2 v;"
 "vec2 d=(gl_FragCoord.xy.xy/v*2-1)*vec2(1,v.y/v.x);"
 "out vec3 m;"
 "float c=acos(-1),f=.01;"
 "vec3 n=vec3(0.,0.,-6.),r=normalize(vec3(d,1)),x=n,b[10],i[3];"
 "float s=0.;\n"
 "#define black vec3(-.015)\n"
 "#define red vec3(.4,.0,.0)\n"
 "#define ground vec3(.03)\n"
 "float t(vec2 v)"
 "{"
   "return v=fract(v*vec2(233.34,851.74)),v+=dot(v,v+23.45),fract(v.x*v.y);"
 "}"
 "vec3 t(vec3 d,vec3 v)"
 "{"
   "float f=cos(v.x),m=sin(v.x);"
   "mat3 r=mat3(vec3(1,0,0),vec3(0,f,-m),vec3(0,m,f));"
   "f=cos(v.y);"
   "m=sin(v.y);"
   "r*=mat3(vec3(f,0,m),vec3(0,1,0),vec3(-m,0,f));"
   "f=cos(v.z);"
   "m=sin(v.z);"
   "r*=mat3(vec3(f,-m,0),vec3(m,f,0),vec3(0,0,1));"
   "return r*d;"
 "}struct material{float d;vec3 col;bool hit;};"
 "float e(vec2 v)"
 "{"
   "return dot(v,v);"
 "}"
 "material e(vec3 v,float f,float m,float d,float r,vec3 x)"
 "{"
   "vec2 n=vec2(length(v.xz),v.y),b=vec2(d,f),k=vec2(d-m,2.*f),s=vec2(n.x-min(n.x,n.y<0.?m:d),abs(n.y)-f),t=n-b+k*clamp(dot(b-n,k)/e(k),0.,1.);"
   "float c=t.x<0.&&s.y<0.?-1.:1.,i=c*sqrt(min(e(s),e(t)))-r;"
   "return material(i,x,false);"
 "}"
 "material e(vec3 v,vec3 d,float m,vec3 f)"
 "{"
   "vec3 r=abs(v)-d;"
   "float n=length(max(r,0.))+min(max(r.x,max(r.y,r.z)),0.)-m;"
   "return material(n,f,false);"
 "}"
 "material t(vec3 v,vec3 f,float d,vec3 m)"
 "{"
   "float r=dot(v,f)+d;"
   "return material(r,m,false);"
 "}"
 "material e(vec3 v,float d,vec3 f)"
 "{"
   "return v=abs(v),material((v.x+v.y+v.z-d)*.57735,f,false);"
 "}"
 "material e(material v,material d)"
 "{"
   "return v.d<d.d?v:d;"
 "}"
 "material l(material v,material d)"
 "{"
   "return v.d>d.d?v:d;"
 "}"
 "float l(float v,float f,float d)"
 "{"
   "float m=max(d-abs(v-f),0.);"
   "return min(v,f)-m*m*.25/d;"
 "}"
 "material l(vec3 v)"
 "{"
   "v=t(t(v,vec3(-.7,0.,-.04)),vec3(0,1.1,0));"
   "v.y-=1.05;"
   "v.x+=.5;"
   "material f=t(v+vec3(0,1.25,0),vec3(0,1,0),1.,ground),d=e(v+vec3(0,.1,0),1.,.15,.25,0,red),r=e(v+vec3(0,.6,0),.05,.3,.3,.05,black),m=e(v+vec3(0,1.,0),.3,.6,.6,.05,black),b=e(v+vec3(0,1.4,0),vec3(.9,.15,.9),.1,black),x=e(v+vec3(1.75,1.34,.75),.05,.55,.45,.02,red);"
   "x.d-=.0005;"
   "material k=e(v+vec3(1.75,1.34,-.75),.05,.55,.45,.02,red);"
   "x.d-=.0005;"
   "material n=e(v+vec3(1.75,1.27,.75),.05,.4,.4,.015,red),s=e(v+vec3(1.75,1.27,-.75),.05,.4,.4,.015,red),y=e(v+vec3(.5,1.85,0),vec3(1.55,0.,1.05),.45,black),z=e(v+vec3(10,sin(v.x*1.8)*.1+2.05,sin(sin(v.x*.7))+.75),vec3(8,0,0),.1,black),i=e(v+vec3(0.,-1.,0.),vec3(0),.5,red);"
   "vec3 c=mod(v,.0001)-5e-05;"
   "material a=e(c,vec3(0.),t(v.xz)*.002,black);"
   "f.d=mix(f.d,a.d,.05);"
   "v=t(t(v,vec3(-.5,0,0)),vec3(0,1.5,0));"
   "material g=material(0.,black,true);"
   "g.d=l(m.d,b.d,.15);"
   "g.d=l(g.d,r.d,.05);"
   "i=e(i,d);"
   "i=e(i,y);"
   "i.d=mix(i.d,a.d,.3);"
   "i=e(i,g);"
   "i=e(i,x);"
   "i=e(i,k);"
   "i=e(i,n);"
   "i=e(i,s);"
   "i=e(i,f);"
   "i=e(i,z);"
   "return i;"
 "}"
 "material t(vec3 v,vec3 d,float m)"
 "{"
   "material r;"
   "while(s<80&&distance(v,x)<m&&!r.hit)"
     "x+=r.d*d,r=l(x),r.hit=r.d<f,s+=1.;"
   "return r;"
 "}"
 "vec3 a(vec3 v)"
 "{"
   "mat3 m=mat3(v,v,v)-mat3(.005);"
   "return normalize(l(v).d-vec3(l(m[0]).d,l(m[1]).d,l(m[2]).d));"
 "}"
 "float a(in vec3 v,in vec3 d,float m,float f,float r)"
 "{"
   "float i=1.,x=1e+20;"
   "for(float b=m;b<f;)"
     "{"
       "float n=l(v+d*b).d;"
       "if(n<.001)"
         "return 0.;"
       "float k=n*n/(2.*x),s=sqrt(n*n-k*k);"
       "i=min(i,r*s/max(0.,b-k));"
       "x=n;"
       "b+=n;"
     "}"
   "return i;"
 "}"
 "vec3 a(vec3 v,vec3 f,vec3 d,float m)"
 "{"
   "vec3 n;"
   "float x[4],s[4];"
   "for(int c=0;c<3;c++)"
     "{"
       "x[c]=max(0.,dot(reflect(b[c],f),r));"
       "s[c]=pow(x[c],64);"
       "float k=a(v,b[c],.1,20.,25);"
       "n+=(x[c]*m*.333+s[c]*m*3)*i[c]*k;"
     "}"
   "return d+n;"
 "}"
 "void main()"
 "{"
   "b[0]=normalize(vec3(0,10,-2.));"
   "b[1]=normalize(vec3(-50,20.,-50.));"
   "b[2]=normalize(vec3(-50,60.,-7.));"
   "vec2 v=vec2(.5,.7);"
   "i[0]=v.xxy*2;"
   "i[1]=v.xyx;"
   "i[2]=v.yxx*.75;"
   "material f=t(n,r,20);"
   "vec3 d=a(x);"
   "if(f.hit)"
     "{"
       "m=f.col;"
       "m=a(x,d,f.col,.1);"
       "if(f.col==black)"
         "{"
           "x-=r*.01;"
           "r=normalize(reflect(r,d));"
           "f=t(x,r,2.5);"
           "if(f.hit)"
             "m=mix(m,a(x,a(x),f.col,.1),.1);"
         "}"
     "}"
   "m*=1.-distance(n,x)*.05;"
   "m=pow(m,vec3(.4545));"
 "}";

#endif // SHADER_H_
